### ISSUE TITLE
แก้จุดผิด

### ISSUE THREAD

**Issue by PPVphilosopher** [monosor/.dev#2]
### Literal Types
ตรงหัวข้อ _Literal Narrowing_
let y = "XYZ"      // **x** มี Type เป็น ...
ในcommentควรเป็น **y**

### ลองเขียนเว็บง่าย ๆ ด้วย TypeScript
ตรงหัวข้อ _refactor type_
interface Results {
  results: **[User]** // Array ของ User -> ควรเป็น results: **User[]**
}

**Comment by narze** [comment]
ขอบคุณครับ อันล่างแก้ไปแล้วใน #3

**Comment by narze** [comment]
Fixed Literal Types typo https://www.monosor.dev/courses/typescript-101/literal-types , closing this
